name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        python-version: [3.12.5]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Atualize para v4

=======
        python-version: ["3.8", "3.9", "3.10", "3.12.5"]
    steps:
    - uses: actions/checkout@v4
>>>>>>> 97d2c0dd8df136980a9b58be639ce2d46fed0e4b
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Atualize para v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
<<<<<<< HEAD
        pip install -r bemol/APIs/pythonproject/requirements.txt

    - name: Run tests
      run: pytest
=======
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
>>>>>>> 97d2c0dd8df136980a9b58be639ce2d46fed0e4b
